"""add per-topic level ladder columns to user_topic_map

Revision ID: 0003
Revises: 0002
Create Date: 2026-08-12

`0001` created `user_topic_map` with a placeholder mastery representation (`mastery_score` +
`streak`) while the module was a scaffold. The designed model is a per-topic **level ladder**:
each candidate holds a level 1-5 per topic (mapping 1:1 onto `question_bank.difficulty`), moved
by two consecutive same-direction signals via a probation flag. That needs five new columns.
`mastery_score` and `streak` are kept as display-only fields — see
`app/modules/user_topic_mapping/models.py`.

Written by hand rather than autogenerated: `0002` renamed the real `daily20_questions` into
`question_bank`, and that table's physical indexes still carry their original `daily20_*` names
which the `QuestionBank` model deliberately does not declare. `alembic revision --autogenerate`
therefore wants to drop and recreate them on every run — see CLAUDE.md, "Question bank".

`server_default` is set on each new column so the ALTERs are safe against a table with existing
rows, then dropped: the application (not the DB) owns the defaults thereafter, since
`initial_topic_level` is configurable per environment.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0003"
down_revision: str | None = "0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_NEW_COLUMNS = ("section", "current_level", "pending_dir", "last_cycle", "times_tested")


def upgrade() -> None:
    op.add_column(
        "user_topic_map",
        sa.Column("section", sa.String(length=32), nullable=False, server_default=""),
    )
    op.add_column(
        "user_topic_map",
        sa.Column("current_level", sa.SmallInteger(), nullable=False, server_default="2"),
    )
    op.add_column(
        "user_topic_map",
        sa.Column("pending_dir", sa.SmallInteger(), nullable=False, server_default="0"),
    )
    op.add_column(
        "user_topic_map",
        sa.Column("last_cycle", sa.Integer(), nullable=False, server_default="0"),
    )
    op.add_column(
        "user_topic_map",
        sa.Column("times_tested", sa.Integer(), nullable=False, server_default="0"),
    )

    for column in _NEW_COLUMNS:
        op.alter_column("user_topic_map", column, server_default=None)

    op.create_index(
        "ix_user_topic_map_user_id_section", "user_topic_map", ["user_id", "section"]
    )


def downgrade() -> None:
    op.drop_index("ix_user_topic_map_user_id_section", table_name="user_topic_map")
    for column in reversed(_NEW_COLUMNS):
        op.drop_column("user_topic_map", column)
