"""add per-question review to user_reports

Revision ID: 0004
Revises: 0003
Create Date: 2026-08-12

`0001` gave `user_reports` the four rendered blocks the prototype's report screen shows above the
fold — headline, tiles, section table, findings, actions. It omitted the largest one: the
per-question review, where each question opens onto the worked method, why the option the
candidate picked looked right, and the shortcut they did not take. That is the part with the most
teaching in it, so it is stored rather than dropped.

Stored rather than re-derived at read time on purpose: a report is a record of what the candidate
was actually shown. Correcting an explanation in `question_bank`, or retiring a question, must
not silently rewrite a report they already read.

Written by hand rather than autogenerated, for the same reason as `0003` — `0002` renamed the
real `daily20_questions` into `question_bank` and its physical indexes still carry `daily20_*`
names the model does not declare, so autogenerate wants to churn them on every run. See
CLAUDE.md, "Config and gotchas".
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0004"
down_revision: str | None = "0003"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.add_column(
        "user_reports",
        sa.Column(
            "questions",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default="[]",
        ),
    )
    # The application supplies the value from here on; the default exists only so the ALTER is
    # safe against rows written before this migration.
    op.alter_column("user_reports", "questions", server_default=None)


def downgrade() -> None:
    op.drop_column("user_reports", "questions")
