"""add user_section_progress, the per-test progress series

Revision ID: 0005
Revises: 0004
Create Date: 2026-08-12

The per-section progress score (`app/modules/user_topic_mapping/progress.py`) was derived on read
from `user_topic_map`, which holds current state only — so it could answer "where does this
candidate stand now" but never "are they improving". This table appends one row per
(candidate, section, evaluated cycle), which is what the dashboard's progress chart plots and what
`GET /v1/progress/{user_id}` serves.

It is a deliberate departure from `user_topic_map`'s "no history here" rule, and CLAUDE.md's
"Data model" section is updated alongside it. The reasoning: a level *movement* stays
reconstructible from `user_test_questions` + `evaluation_result` and is not duplicated, but the
0-100 figure the candidate is shown is a different thing — recomputing the whole series on read
would reach across two other modules' tables and risk producing a number that disagrees with the
one already on screen.

Written by hand rather than autogenerated, for the same reason as `0003` and `0004` — `0002`
renamed the real `daily20_questions` into `question_bank` and its physical indexes still carry
`daily20_*` names the model does not declare, so autogenerate wants to churn them on every run.
See CLAUDE.md, "Config and gotchas".
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0005"
down_revision: str | None = "0004"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "user_section_progress",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.Column("section", sa.String(length=32), nullable=False),
        sa.Column("cycle_version", sa.Integer(), nullable=False),
        sa.Column("current_level", sa.SmallInteger(), nullable=False),
        sa.Column("raw_score", sa.Float(), nullable=False),
        sa.Column("progress_score", sa.Float(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name="pk_user_section_progress"),
        sa.UniqueConstraint(
            "user_id", "section", "cycle_version", name="uq_user_section_progress_cycle"
        ),
    )
    op.create_index("ix_user_section_progress_user_id", "user_section_progress", ["user_id"])


def downgrade() -> None:
    op.drop_index("ix_user_section_progress_user_id", table_name="user_section_progress")
    op.drop_table("user_section_progress")
